service: pytemp
provider:
  name: aws
  region: ap-northeast-1
  runtime: python2.7
  profile: ${env:AWS_PROFILE,'default'}

functions:
  pytemp:
    handler: app/handler.lambda_handler
    events:
      - http:
          path: /generate
          method: post
          integration: lambda
          response:
            contentHandling: CONVERT_TO_BINARY
plugins:
  - serverless-prune-plugin
  - serverless-python-requirements
  - serverless-offline-python
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  pythonRequirements:
    dockerizePip: true 
    slim: true
    zip: true
  apigwBinary:
    types:
      - "application/pdf"
      - "application/json"
  prune:
    automatic: true
    number: 3

package:
  include:
    - app/*
    - lib/*
    - fonts/**
  exclude:
    - .python-version
    - app/*.pyc
    - app/haru/*.pyc
    - node_modules/**
    - package.json
    - package-lock.json
    - requirements.txt
    - tmp/**
    - tools/**
