service: pytemp
provider:
  name: aws
  region: ap-northeast-1
  runtime: python3.5
  profile: ${env:AWS_PROFILE,'default'}

functions:
  pytemp:
    handler: app/handler.lambda_handler
    events:
      - http:
          path: /generate
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    zip: true

package:
  include:
    - app/*
    - fonts/**
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json
    - requirements.txt
    - tmp/**
    - tools/**
